application: or-bootcamp
version: 1
runtime: python
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static/css
  static_dir: static/css

- url: .*
  script: main.py

